name: CI Pipeline

on:
  push

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pipenv
        run: pipx install pipenv
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0
          architecture: x64
          cache: 'pipenv'
      - name: Install dependencies
        run: pipenv install --dev
      - uses: chartboost/ruff-action@v1
